name: Deploy Azure Storage Account
on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
    AZURE_RESOURCE_GROUP: 'myghRG'
    AZURE_STORAGE_ACCOUNT: 'sridharbghmystorageaccount${{ github.run_number }}'
    LOCATION: 'eastus'

jobs:
  deployARMTemplate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Storage Account ARM Template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
          template: ./StorageAccount/azuredeploy.json
          parameters: ./StorageAccount/azuredeploy.parameters.json 
          failOnStdErr: false
